service: my-serverless-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  getData:
    handler: handler.getData
    events:
      - http:
          path: get-data
          method: get
          cors: true

plugins:
  - serverless-offline

